CLASS ICON_AA INHERIT Icon
CONSTRUCTOR() 
   SUPER(ResourceID{"ICON_AA", _GetInst()})
return self

END CLASS
CLASS ICON_COMPTES INHERIT Icon
CONSTRUCTOR() 
   SUPER(ResourceID{"ICON_COMPTES", _GetInst()})
return self

END CLASS
CLASS ICON_DEPENSE INHERIT Icon
CONSTRUCTOR() 
   SUPER(ResourceID{"ICON_DEPENSE", _GetInst()})
return self

END CLASS
CLASS ICON_NEW INHERIT Icon
CONSTRUCTOR() 
   SUPER(ResourceID{"ICON_NEW", _GetInst()})
return self

END CLASS
CLASS ICON_RECETTE INHERIT Icon
CONSTRUCTOR() 
   SUPER(ResourceID{"ICON_RECETTE", _GetInst()})
return self


END CLASS
