#include "Dlg Input.vh"
USING VO



STATIC DEFINE INPUTBOX_VALUE1TXT := 100
STATIC DEFINE INPUTBOX_VALUE1 := 101
STATIC DEFINE INPUTBOX_VALUE2 := 102
STATIC DEFINE INPUTBOX_VALUE2TXT := 103
STATIC DEFINE INPUTBOX_VALUE3TXT := 104
STATIC DEFINE INPUTBOX_VALUE3 := 105
STATIC DEFINE INPUTBOX_VALUE4 := 106
STATIC DEFINE INPUTBOX_VALUE4TXT := 107
STATIC DEFINE INPUTBOX_OKPB := 108
STATIC DEFINE INPUTBOX_CANCELPB := 109
PARTIAL CLASS InputBox INHERIT DIALOGWINDOW
	EXPORT oDCValue1Txt AS FIXEDTEXT
	EXPORT oDCValue1 AS SINGLELINEEDIT
	EXPORT oDCValue2 AS SINGLELINEEDIT
	EXPORT oDCValue2Txt AS FIXEDTEXT
	EXPORT oDCValue3Txt AS FIXEDTEXT
	EXPORT oDCValue3 AS SINGLELINEEDIT
	EXPORT oDCValue4 AS SINGLELINEEDIT
	EXPORT oDCValue4Txt AS FIXEDTEXT
	EXPORT oCCOkPB AS PUSHBUTTON
	EXPORT oCCCancelPB AS PUSHBUTTON

	// {{%UC%}} User code starts here (DO NOT remove this line)  

METHOD CancelPB( ) 
	self:EndDialog( 0 )
return self	

CONSTRUCTOR(oParent,uExtra)

	SELF:PreInit(oParent,uExtra)

	SUPER(oParent , ResourceID{"InputBox" , _GetInst()} , TRUE)

	SELF:oDCValue1Txt := FIXEDTEXT{SELF , ResourceID{ INPUTBOX_VALUE1TXT  , _GetInst() } }
	SELF:oDCValue1Txt:HyperLabel := HyperLabel{#Value1Txt , "Value1" , NULL_STRING , NULL_STRING}

	SELF:oDCValue1 := SINGLELINEEDIT{SELF , ResourceID{ INPUTBOX_VALUE1  , _GetInst() } }
	SELF:oDCValue1:HyperLabel := HyperLabel{#Value1 , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCValue2 := SINGLELINEEDIT{SELF , ResourceID{ INPUTBOX_VALUE2  , _GetInst() } }
	SELF:oDCValue2:HyperLabel := HyperLabel{#Value2 , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCValue2Txt := FIXEDTEXT{SELF , ResourceID{ INPUTBOX_VALUE2TXT  , _GetInst() } }
	SELF:oDCValue2Txt:HyperLabel := HyperLabel{#Value2Txt , "Value2" , NULL_STRING , NULL_STRING}

	SELF:oDCValue3Txt := FIXEDTEXT{SELF , ResourceID{ INPUTBOX_VALUE3TXT  , _GetInst() } }
	SELF:oDCValue3Txt:HyperLabel := HyperLabel{#Value3Txt , "Value3" , NULL_STRING , NULL_STRING}

	SELF:oDCValue3 := SINGLELINEEDIT{SELF , ResourceID{ INPUTBOX_VALUE3  , _GetInst() } }
	SELF:oDCValue3:HyperLabel := HyperLabel{#Value3 , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCValue4 := SINGLELINEEDIT{SELF , ResourceID{ INPUTBOX_VALUE4  , _GetInst() } }
	SELF:oDCValue4:HyperLabel := HyperLabel{#Value4 , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCValue4Txt := FIXEDTEXT{SELF , ResourceID{ INPUTBOX_VALUE4TXT  , _GetInst() } }
	SELF:oDCValue4Txt:HyperLabel := HyperLabel{#Value4Txt , "Value4" , NULL_STRING , NULL_STRING}

	SELF:oCCOkPB := PUSHBUTTON{SELF , ResourceID{ INPUTBOX_OKPB  , _GetInst() } }
	SELF:oCCOkPB:HyperLabel := HyperLabel{#OkPB , "&Ok" , NULL_STRING , NULL_STRING}

	SELF:oCCCancelPB := PUSHBUTTON{SELF , ResourceID{ INPUTBOX_CANCELPB  , _GetInst() } }
	SELF:oCCCancelPB:HyperLabel := HyperLabel{#CancelPB , "&Cancel" , NULL_STRING , NULL_STRING}

	SELF:Caption := "Parameters"
	SELF:HyperLabel := HyperLabel{#InputBox , "Parameters" , NULL_STRING , NULL_STRING}

	SELF:PostInit(oParent,uExtra)

RETURN


METHOD OkPB( ) 
	SELF:EndDialog( 1 )
return self
END CLASS

